# Namespace for WordPress
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---

# ConfigMap for WordPress configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
  labels:
        id: c0904322   # replace with your actual college ID
        app: nginx
        env: dev
data:
  db-host: mariadb.mariadb.svc.cluster.local  # Use MariaDB service's fully qualified domain name (FQDN)
  db-user: wordpress
  db-name: wordpress

---

# Secret for WordPress sensitive data (MySQL password)
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
  labels:
        id: c0904322   # replace with your actual college ID
        app: nginx
        env: dev
type: Opaque
data:
  db-password: d29yZHByZXNz  # Replace with base64-encoded password

---

# Deployment for WordPress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
  labels:
        id: c0904322   # replace with your actual college ID
        app: nginx
        env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: db-host
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: db-user
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: wordpress-config
                  key: db-name
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db-password

---

# Service to expose WordPress as LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress
  labels:
        id: c0904322   # replace with your actual college ID
        app: nginx
        env: dev
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
