apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---

# ConfigMap for WordPress configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  db-host: mariadb.mariadb.svc.cluster.local  # Use MariaDB service's fully qualified domain name (FQDN)
  db-user: wordpress
  db-name: wordpress
