# Namespace for WordPress
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress

---

# Secret for WordPress sensitive data (MySQL password)
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
data:
  db-password: d29yZHByZXNz  # Replace with base64-encoded password
