# Namespace for MariaDB
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb


---

# Secret for MariaDB sensitive data (root and user passwords)
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  mysql-root-password: d29yZHByZXNz   # Replace with base64-encoded root password
  mysql-password: d29yZHByZXNz        # Replace with base64-encoded user password