apiVersion: v1
kind: Namespace
metadata:
  name: mariadb

---

# ConfigMap for MariaDB configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: mariadb
data:
  mysql-database: wordpress
  mysql-user: wordpress